### ISSUE TITLE
Global review and switching to PoS over time

### ISSUE THREAD

**Issue by merwane** [bitcoinroyale/whitepaper#18]

**Comment by ianduoteli** [comment]
Very interesting discussion, do you mind placing the contents of the Google Doc inside the comments? I think it will make it more accessible

**Comment by merwane** [comment]
_Sure, here you go:_

**Overview:**

After spending two days reading Bitcoin Royale’s whitepaper and its source code, I understood the core vision of the project, a more optimized, decentralized, secure digital store of value. As I understood, Royale’s main advantage over Bitcoin core is optimization as an asset rather than a cash system. In the following paragraphs, I will do a technical and economical constructive critic of the project.

### Bitcoin Royale: The psychological aspect

The main technical difference with Bitcoin core being delayed confirmation for better control over assets movements, Bitcoin Royale’s mining system should be implemented with a proof-of-stake algorithm instead of proof-of-work, here’s why:

Royale’s vision is to store value for the long term, meaning nodes with large balances will be more afraid of getting punished by the PoS algorithm.
Proof-of-work encourages competition and volatility because of programmed harving whereas proof-of-stake is more focused on stability, and since the goal is to store value without high volatility, nodes will be more confident to a stable system which scales horizontally and is agnostic of outside factors such as Moore’s law.
It encourages nodes to store value in a trustless way since they’re aware of the general stability of the protocol compared to PoW, as we can see with XRP and Ethereum Istanbul, which aren’t meant to be cash systems.

Of course, using proof-of-stake comes at a cost. Since the network will not incentivize to competition between validators, which in this case are the wealthiest nodes, it will solely repose on rewarding them with high transaction fees. But again, since the project’s main vision is to create a value store rather than a cash system, high transaction fees should be normal since transactions aren’t as usual as in other Blockchains.

### Economically, things get more difficult:

Bitcoin Royale is on the extreme side of the Bitcoin spectrum where Bitcoin cash as a digital cash system with lower transaction fees and faster transactions is on the other end.  Bitcoin core is in the middle, initially proposing itself as a cash system, then becoming a hybrid between the two.

As the transactions will be less frequent than on other Blockchains, you have to assume that your daily trading volume will be significantly smaller. This can be a penalty when it comes to the coin’s global ranking on platforms like Coinmarketcap. I suggest reducing the delay to 12 hours.

If you opt for using a PoW algorithm, you have to find a better setting between the total supply, coins shardability and mining difficulty. Also, since your coin is based on Bitcoin and is a limited asset, it has a deflationary nature, therefore, you should take advantage of this by reducing the total supply while keeping the same mining difficulty.

Whether you opt for PoW or PoS, I advise you to change the shardability of your coin. Economically speaking, creating a less divisible asset increases its value during recessions. Think of it as Bitcoin core being gold (which is a highly divisible asset), and Bitcoin Royale being diamonds (less divisible asset with higher value during recessions). The example may seem obscure but this is why civil wars in Africa are financed by diamonds and not by gold, value increases on recessions.

Why am I thinking of recessions? Simply because your coin is meant to stay securely stored and highly exchanged rather than being used for commercial purposes. Which means its nature is to stay alive longer (in theory).

### Technical point of view:

The coin’s mempool is obviously expected to be significantly busier than Bitcoin’s due to its delaying nature, even if it has fewer nodes. This should be taken into account since the number of unconfirmed transactions on the Blockchain can also have an impact on mining time. In fact, this is the main technical reason which made me think that it would be better to implement a PoS algorithm.

It might sound counterintuitive at first, but since the network can process around ~6 transactions per second at peak, you should reduce this so that the mempool doesn’t get flooded. Another point is that keeping 6 TXPS with a low transaction volume will considerably decrease transaction fees, which is probably not what we want. 

You can achieve all of this by increasing the mining difficulty while reducing the confirmation time, as mentioned earlier.

**On a more personal note:**

I think Bitcoin Royale can definitely work if it’s launched at the right time, with a good philosophy. By this, I mean that no pre-mined coins should be allowed. 

Also, I think you should drop the “e” at the end of Royale, having fewer characters is always better from my perspective. :)
